alias ls='ls -FG --color'
alias ll='ls -l --color'
alias lrt='ls -lrt --color'
alias la='ls -al --color'
alias h='history'
alias p='pwd'
alias l='ls -l --color'
alias ezlogin='ssh login-1'
alias gems='cd $GEM_HOME/gems'
alias vi='vim'
alias be='bundle exec'
alias setname='tmux rename-session `basename $PWD`'

alias dc="docker-compose"
alias dps="docker ps"
alias dpsn='docker ps --format="{{.Names}}"'
